services:
  postgres:
    image: postgres:16
    container_name: haven_postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - haven_network

  backend:
    build: ./haven_backend
    container_name: haven_backend
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - postgres
    env_file:
      - .env
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
    networks:
      - haven_network

  frontend:
    build: ./haven_client_frontend
    container_name: haven_client_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "80:80"
      - "443:443"
    networks:
      - haven_network
    volumes:
      - letsencrypt_data:/etc/letsencrypt
      - certbot_www:/var/www/certbot

  certbot:
    image: certbot/certbot
    container_name: haven_certbot
    volumes:
      - letsencrypt_data:/etc/letsencrypt
      - certbot_www:/var/www/certbot

volumes:
  postgres_data:
  letsencrypt_data:
  certbot_www:

networks:
  haven_network: